trigger:
- main

pool: 'UAT-Pipeline-Agents'

steps:

- task: TerraformInstaller@1
  displayName: 'terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'D:\git_revision\3rd-Aug-PPL'
    backendServiceArm: 'nits-federated-app'
    backendAzureRmStorageAccountName: 'nitsstg1'
    backendAzureRmContainerName: 'niteshcontainer'
    backendAzureRmKey: 'r.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'D:\git_revision\3rd-Aug-PPL'
    environmentServiceNameAzureRM: 'nits-federated-app'

