trigger:
- main

pool:
  vmImage: 'UAT-Pipeline-Agents'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- task: TerraformTaskV5@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'nits-federated-app>'
    backendAzureRmResourceGroupName: 'nits1'
    backendAzureRmStorageAccountName: 'nitsstg1'
    backendAzureRmContainerName: 'niteshcontainer'
    backendAzureRmKey: 'remote.tfstate'

- task: TerraformTaskV5@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'nits-federated-app'

- task: TerraformTaskV5@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'nits-federated-app'
    allowTelemetryCollection: false
