trigger:
 branches:
   include:
     - feature/*
     - main

pool: 'UAT-Pipeline-Agents'

variables:
  nitesh_path: 'D:\\git_revision\\3rd-Aug-PPL'
  service_connection: 'nits-federated-app'
       
steps:
- task: TerraformInstaller@1
  displayName: Terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'D:\\git_revision\\3rd-Aug-PPL'
    backendServiceArm: 'nits-federated-app'
    backendAzureRmStorageAccountName: 'nitsstg1'
    backendAzureRmContainerName: 'niteshcontainer'
    backendAzureRmKey: 'pp.tfstate'

- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: 'D:\\git_revision\\3rd-Aug-PPL'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'D:\\git_revision\\3rd-Aug-PPL'
    environmentServiceNameAzureRM: 'nits-federated-app'

- task: TerraformTask@5
  displayName: terraform apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'D:\\git_revision\\3rd-Aug-PPL'
    environmentServiceNameAzureRM: 'nits-federated-app'