trigger:
- main

pool:
  vmImage: 'my_agent2'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- task: TerraformTaskV5@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'

- task: TerraformTaskV5@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'nits-federated-app'

- task: TerraformTaskV5@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'nits-federated-app'
    allowTelemetryCollection: false
