trigger:
- main

pool: 'UAT-Pipeline-Agents'

steps:
- task: TerraformInstaller@1
  displayName: 'install terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'D:\git_revision\3rd-Aug-PPL'
    backendServiceArm: 'nits-federated-app'
    backendAzureRmStorageAccountName: 'nitsstg1'
    backendAzureRmContainerName: 'niteshcontainer'
    backendAzureRmKey: 'remote.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'D:\git_revision\3rd-Aug-PPL'
    environmentServiceNameAzureRM: 'nits-federated-app'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'D:\git_revision\3rd-Aug-PPL'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'nits-federated-app'
