trigger:
- main

pool: 'UAT-Pipeline-Agents'

variables:
  nitesh_path: 'D:\git_revision\3rd-Aug-PPL'
  service_connection: 'nits-federated-app'


steps:
- task: TerraformInstaller@1
  displayName: 'install terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(nitesh_path)
    backendServiceArm: $(service_connection)
    backendAzureRmStorageAccountName: 'nitsstg1'
    backendAzureRmContainerName: 'niteshcontainer'
    backendAzureRmKey: 'remote.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(nitesh_path)
    environmentServiceNameAzureRM: $(service_connection)
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(nitesh_path)
    environmentServiceNameAzureRM: $(service_connection)

